// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY_WEB'),
    appId: '1:1042683285867:web:689fecb64ded5e5468bc2e',
    messagingSenderId: '1042683285867',
    projectId: 'homeguard-aa17f',
    authDomain: 'homeguard-aa17f.firebaseapp.com',
    storageBucket: 'homeguard-aa17f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY_ANDROID'),
    appId: '1:1042683285867:android:f8610ea7decab53968bc2e',
    messagingSenderId: '1042683285867',
    projectId: 'homeguard-aa17f',
    storageBucket: 'homeguard-aa17f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY_IOS'),
    appId: '1:1042683285867:ios:ee6529d51d1a693968bc2e',
    messagingSenderId: '1042683285867',
    projectId: 'homeguard-aa17f',
    storageBucket: 'homeguard-aa17f.firebasestorage.app',
    iosBundleId: 'com.example.homeguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY_IOS'),
    appId: '1:1042683285867:ios:ee6529d51d1a693968bc2e',
    messagingSenderId: '1042683285867',
    projectId: 'homeguard-aa17f',
    storageBucket: 'homeguard-aa17f.firebasestorage.app',
    iosBundleId: 'com.example.homeguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY_WEB'),
    appId: '1:1042683285867:web:ae37893defa414fb68bc2e',
    messagingSenderId: '1042683285867',
    projectId: 'homeguard-aa17f',
    authDomain: 'homeguard-aa17f.firebaseapp.com',
    storageBucket: 'homeguard-aa17f.firebasestorage.app',
  );

}